spring.application.name=hr-management-api
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_portal
spring.datasource.username=postgres
spring.datasource.password=Ved@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080